on: push
name: example
jobs:
  job:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        
      - run: echo hello > artifact.txt

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: artifact.txt
        
      - name: flakey
        run: exit 1 # lol look how unreliable this build is
        
      - name: sshst
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          set -eux
          curl -o sshst.deb -L https://github.com/aidansteele/sshstdemo/releases/download/1/sshst_v0.1.14-next_linux_amd64.deb
          sudo dpkg -i sshst.deb
          sshst listen --web-ok --notify aidansteele -g @glassechidna/Mateys -g Mongooz -g UniqueElphie
