on: 
  push: {}
  deployment: {}
name: example
jobs:
  job:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        
      - run: echo hello > artifact.txt

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: artifact.txt
        
      - name: flakey
        run: exit 1 # lol look how unreliable this build is
        
      - name: sshst
        if: failure()
        uses: ./actions/sshst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowedUsers: glassechidna/Mateys Mongooz UniqueElfie ${{ github.actor }}
